
// THIS FILE IS AUTOMATICALLY GENERATED. TO CHANGE IT'S CONTENT, CHANGE THE RESPECTIVE JSON SCHEMA AND REBUILD THE SCHEMATICS.

export interface Schema {
    /**
     * The browser integration framework to use.
     */
    browserIntegrationFramework?: string;
    /**
     * The path within the project. Defaults to 'Feature' when using Cucumber.
     */
    directory?: string;
    /**
     * The name of the project to which your want to add serenity-js
     */
    project?: string;
    /**
     * The testing framework to use.
     */
    testFramework?: string;
}
