const { quicktype, InputData, JSONSchemaInput, TypeScriptTargetLanguage } = require("quicktype-core");
const fs = require("fs");
const glob = require("glob");

const header = `
// THIS FILE IS AUTOMATICALLY GENERATED. TO CHANGE IT'S CONTENT, CHANGE THE RESPECTIVE JSON SCHEMA AND REBUILD THE SCHEMATICS.

`;

async function main() {
    const schemas = glob.sync('schematics/**/schema.json');
    await Promise.all(schemas.map(async jsonSchemaPath => {
        const inputData = new InputData();
        const source = { name: 'Schema', schema: fs.readFileSync(jsonSchemaPath, { encoding: 'utf-8' }) };
        await inputData.addSource('schema', source, () => new JSONSchemaInput(undefined));
        const lang = new TypeScriptTargetLanguage();
        const { lines } = await quicktype({ lang, inputData, alphabetizeProperties: true, rendererOptions: { 'just-types': true, 'explicit-unions': true, 'ancronym-style': 'camel' } });
        const outPath = jsonSchemaPath.replace(/\.json$/, '.ts');
        fs.writeFileSync(outPath, `${header}${lines.join('\n')}`, { encoding: 'utf-8'});
    }));
}

main();
