
// THIS FILE IS AUTOMATICALLY GENERATED. TO CHANGE IT'S CONTENT, CHANGE THE RESPECTIVE JSON SCHEMA AND REBUILD THE SCHEMATICS.

export interface Schema {
    directory?: string;
    /**
     * The name of the question
     */
    name: string;
    /**
     * The name of the project to which the question will be added
     */
    project?: string;
}
